name: blinky test
version: 1
author: Sergio Gasquez Arcos

steps:
  - wait-serial: "Hello world!"
  - delay: 100ms
  - expect-pin:
      part-id: esp
      pin: 7
      value: 0
  - delay: 550ms
  - expect-pin:
      part-id: esp
      pin: 7
      value: 1
