name: button test
version: 1
author: Sergio Gasquez Arcos

steps:
  - wait-serial: "Hello world!"
  - delay: 100ms
  # Press once
  - set-control:
      part-id: btn1
      control: pressed
      value: 1
  - delay: 50ms
  - expect-pin:
      part-id: esp
      pin: 7
      value: 0
  - set-control:
      part-id: btn1
      control: pressed
      value: 0
  - delay: 50ms
  - expect-pin:
      part-id: esp
      pin: 7
      value: 1
