name: http-client test
version: 1
author: Sergio Gasquez Arcos

steps:
    - wait-serial: "Wait to get connected"
    - wait-serial: "Wait to get an ip address"
    - wait-serial: "Making HTTP request"
    - wait-serial: "< Hello fellow Rustaceans! >"
