[wokwi]
version = 1
# Exercise
# firmware = "target/riscv32imc-unknown-none-elf/release/button"
# elf = "target/riscv32imc-unknown-none-elf/release/button"

# Solution
firmware = 'target/riscv32imc-unknown-none-elf/release/examples/button'
elf = 'target/riscv32imc-unknown-none-elf/release/examples/button'
