[package]
edition      = "2024"
name         = "no_std-training"
rust-version = "1.88"
version      = "0.1.0"

[dependencies]
embassy-executor = "0.10.0"
embassy-net = { version = "0.9.1", features = [
  "dhcpv4",
  "dns",
  "medium-ethernet",
  "tcp",
  "udp",
] }
embassy-time = "0.5.1"
embedded-io-async = "0.7.0"
esp-alloc = "0.10.0"
esp-backtrace = { version = "0.19.0", features = [
  "esp32c3",
  "panic-handler",
  "println",
] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32c3"] }
esp-hal = { version = "1.1.1", features = ["esp32c3", "log-04", "unstable"] }
esp-println = { version = "0.17.0", features = ["esp32c3", "log-04"] }
esp-radio = { version = "0.18.0", features = [
  "esp32c3",
  "log-04",
  "unstable",
  "wifi",
] }
esp-rtos = { version = "0.3.0", features = [
  "embassy",
  "esp-radio",
  "esp32c3",
  "log-04",
] }
log = "0.4.29"
shtcx = { git = "https://github.com/SergioGasquez/shtcx-rs", rev = "9207153f1042b1e1d8e1bbb6f7bba2281c4a13f4", features = ["async"] }
static_cell = "2.1.1"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug         = 2
lto           = 'fat'
opt-level     = 's'
