[package]
name = "http-client"
version = "0.1.0"
authors = ["Sergio Gasquez <sergio.gasquez@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
# TODO: Explain
resolver = "2"

# TODO: Explain
[profile.release]
# Explicitly disable LTO which the Xtensa codegen backend has issues
lto = "off"
opt-level = 3
[profile.dev]
lto = "off"

[dependencies]
embassy-executor = "0.10.0"
embassy-net = { version = "0.8.0", features = [
    "dhcpv4",
    "dns",
    "medium-ethernet",
    "tcp",
] }
embassy-time = "0.5.0"
esp-alloc = "0.10.0"
esp-hal = { version = "1.1.0", features = [
    "esp32c3",
    "log-04",
    "unstable",
] }
esp-backtrace = { version = "0.19.0", features = [
    "esp32c3",
    "panic-handler",
    "println",
] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32c3"] }
esp-println = { version = "0.17.0", features = ["esp32c3", "log-04"] }
esp-rtos = { version = "0.3.0", features = ["esp32c3", "embassy", "esp-radio", "log-04"] }
esp-radio = { version = "0.18.0", features = [
    "esp32c3",
    "log-04",
    "unstable",
    "wifi",
] }
reqwless = { version = "0.14.0", default-features = false }
static_cell = "2.1.0"
